version: '2.0'
services:
  web:
    build: ./
    expose:
      - "8000"
    volumes:
      - /web
    command: gunicorn  web:app
    links:
      - db

  nginx:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile-Nginx
    ports:
      - "80:80"
    links:
      - web:web



  telegram:
    build:
      context: .
      dockerfile: ./Dockerfile-Telegram
    volumes:
      - /telegram-bot
    command: python3 -u base.py
    links:
      - db
  db:
    image: mongo:latest
