web:
  restart: always
  build: ./web
  expose:
    - "8000"

  volumes:
    - /usr/src/app/static
  env_file: .env
  command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
  links:
      - db
nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/static
  volumes_from:
    - web
  links:
    - web:web

telegram-web:
  build: ./telegram-bot
  command: python3 base.py
  links:
    - db
db:
  image: mongo:latest
